---
- hosts: appserver
  become: yes
  tasks:
  - name: install git, wget and tree on nodes using loops
    apt: 
    name: "{{ item }}"
    state: present
    with items:
     - git
     - wget
     - tree